Kitware/nrtk-explorer

nrtk_explorer/app/embeddings.py, nrtk_explorer/library/dimension_reducers.py, nrtk_explorer/library/embeddings_extractor.py, nrtk_explorer/widgets/nrtk_explorer.py, tests/test_embeddings.py, vue-components/src/components/ScatterPlot.vue
[Peek 2024-01-17 20-54.webm](https://github.com/Kitware/nrtk-explorer/assets/939798/c668cf54-e70a-4c40-8caf-aeffcb7f0ace)
=> Transforms plot shows origin and transformations

nrtk_explorer/app/core.py, nrtk_explorer/app/embeddings.py, nrtk_explorer/app/transforms.py, nrtk_explorer/app/ui/image_list.py, nrtk_explorer/library/embeddings_extractor.py, nrtk_explorer/widgets/nrtk_explorer.py, tests/test_embeddings.py, vue-components/src/components/ImageDetection.vue, vue-components/src/components/ScatterPlot.vue
Refactor image id handling.
- Moves logic to the core application (Random selection and number of images to load).
- Fixes wrong transformation when using random selection
- Connects plots and thumbnails so that hovering is reflected.
- Further improving performance by sharing a cache of the feature extractions between the source and transformation dataset.
[Peek 2024-01-24 20-01.webm](https://github.com/Kitware/nrtk-explorer/assets/939798/c43c624c-d190-4d56-8d49-f9a8f190f20e)
=> Refactor image id handling

vue-components/package-lock.json, vue-components/src/components/ScatterPlot.vue
Resolves: https://github.com/Kitware/nrtk-explorer/security/dependabot/7
This also solves a bug in which the setsequence was not working.
=> update npm pkgs

nrtk_explorer/app/embeddings.py, nrtk_explorer/app/main.py, nrtk_explorer/library/dimension_reducers.py, nrtk_explorer/library/embeddings_extractor.py, nrtk_explorer/library/ml_models.py, pyproject.toml, tests/test_embeddings.py
|   #Samples |   batch_size |   ExecTime(sec) |
|------------|--------------|-----------------|
|         10 |            1 |      0.00187263 |
|         10 |            8 |      0.00150571 |
|         10 |           16 |      0.00143538 |
|         10 |           32 |      0.0014331  |
|        100 |            1 |      0.00195474 |
|        100 |            8 |      0.00148716 |
|        100 |           16 |      0.00144078 |
|        100 |           32 |      0.00141375 |
|        500 |            1 |      0.00214768 |
|        500 |           64 |      0.00144773 |
=> add batching and make it a param

nrtk_explorer/app/core.py, nrtk_explorer/app/embeddings.py, nrtk_explorer/widgets/nrtk_explorer.py, vue-components/package.json, vue-components/src/components/ScatterPlot.vue
=> add cli flag for passing paths of datasets

.flake8, .github/workflows/ci.yml, nrtk_explorer/library/ml_models.py, nrtk_explorer/library/nrtk_transforms.py, nrtk_explorer/library/transforms.py, pyproject.toml
@alesgenova there are several typing errors here and there, I am trying to make the library python file typing compliant. There are some issues in `nrtk_explorer/library/nrtk_transforms.py` which I am not sure how to fix, feel free to push to this branch.
=> mypy: Add python typing CI

nrtk_explorer/app/core.py, nrtk_explorer/app/embeddings.py, nrtk_explorer/app/transforms.py, nrtk_explorer/app/ui/image_list.py, vue-components/src/components/ImageDetection.vue
=> enable hovering highlight in all components

vue-components/src/components/ScatterPlot.vue, vue-components/src/utilities/colors.ts
[Peek 2024-03-04 15-51.webm](https://github.com/Kitware/nrtk-explorer/assets/939798/92573261-f32f-42d9-bfeb-f7b35b4468af)
=> toggle hide source points in scatterplot

nrtk_explorer/app/embeddings.py, nrtk_explorer/app/transforms.py, nrtk_explorer/app/ui/image_list.py, nrtk_explorer/widgets/nrtk_explorer.py, vue-components/src/components/ImageDetection.vue, vue-components/src/components/ScatterPlot.vue
[Peek 2024-03-09 18-54.webm](https://github.com/Kitware/nrtk-explorer/assets/939798/2c952273-7267-48f9-aadb-d7aa389d9e88)
=> Rework point highlighting to consider src and transformations

nrtk_explorer/app/core.py, nrtk_explorer/module/.gitignore, nrtk_explorer/module/__init__.py, vue-components/public/styles.css, vue-components/src/components/ScatterPlot.vue
Also, now when scrolling a panel the rest of the UI is not affected (see end of the video)
[Screencast from 03-12-2024 11:03:04 PM.webm](https://github.com/Kitware/nrtk-explorer/assets/15913822/c4445271-9407-4b38-8129-73adef7abed7)
=> Allow user to resize the UI panels

src/nrtk_explorer/app/core.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/__init__.py, src/nrtk_explorer/app/ui/collapsible_card.py, src/nrtk_explorer/app/ui/layout.py, src/nrtk_explorer/library/nrtk_transforms.py
If starting app with `nrtk_explorer --hot-reload`, then a button appears in the upper right to reload the ui modules and re-run Engine.ui method.
=> Hot-reload for UI and support latest NRTK API

pyproject.toml, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/library/nrtk_transforms.py, src/nrtk_explorer/library/object_detector.py, tests/conftest.py, tests/test_embeddings.py, vue-components/src/components/ImageDetection.vue
We need this backported to release the Conda nrtk-explorer package. I backported only the fixes so that we only increase the patch release number in the following release.
We want to hold having a minor release until we have more features merged
=> Backport fixes release

src/nrtk_explorer/app/core.py, src/nrtk_explorer/app/embeddings.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/__init__.py, src/nrtk_explorer/app/ui/image_list.py, src/nrtk_explorer/app/ui/layout.py, src/nrtk_explorer/widgets/nrtk_explorer.py, vue-components/package.json, vue-components/src/components/ImageDetection.vue, vue-components/src/components/ScatterPlot.vue, vue-components/src/types/index.ts
=> feat(image_list): group original and transformed images

vue-components/package-lock.json, vue-components/package.json
These will address the security issues.
=> chore: update npm packages

pyproject.toml, src/nrtk_explorer/app/core.py, src/nrtk_explorer/app/embeddings.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/library/coco_utils.py, src/nrtk_explorer/library/dataset.py, tests/test_embeddings.py
This PR uses kwcoco for opening coco files.
This will allow our app to support both standard COCO files and KWCOCO files.
=> feat: use kwcoco for coco datasets

src/nrtk_explorer/library/dataset.py
get_dataset() returns a CocoDataset, not a Dataset.
=> fix(dataset): prefer implicit return types

.flake8, src/nrtk_explorer/app/core.py, src/nrtk_explorer/app/image_ids.py, src/nrtk_explorer/app/image_server.py, src/nrtk_explorer/app/trame_utils.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/image_list.py, src/nrtk_explorer/library/dataset.py, vue-components/src/components/ImageDetection.vue
Progressivly pushes computed annotations to browser/client.  Just feels faster, actually slower =)
=> Fast image list

src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/layout.py, src/nrtk_explorer/library/embeddings_extractor.py, src/nrtk_explorer/library/object_detector.py
=> embeddings,object_detector: add GPU OOM recovering fix

src/nrtk_explorer/library/nrtk_transforms.py
=> Fix type checks when missing libraries

src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/image_list.py, src/nrtk_explorer/app/ui/layout.py, vue-components/src/components/ImageDetection.vue
=> Show Annotations switch

src/nrtk_explorer/app/embeddings.py
=> fix(embeddings): disable transforms switch hides points

src/nrtk_explorer/app/images/stateful_annotations.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/layout.py
Adds 2 more Object Detection models from HuggingFace.  Clears old model annotations when switching models via the select dropdown.
related to #89
=> Add more object detection models

README.md
=> docs(README): update screenshot

src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/library/debounce.py
=> fix(debounce): only await coroutines

src/nrtk_explorer/library/nrtk_transforms.py, src/nrtk_explorer/library/nrtk_transforms.yaml, tests/test_object_detector.py, tests/test_transforms.py, tests/utils.py
New version of nrtk broke old sensor scenerio parameter factory we had.
=> fix(pybsm): update arguments to PybsmPerturber

src/nrtk_explorer/app/images/image_meta.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/image_list.py
Use state passed to ImageList via template rather than trame.app.get_server
=> ImageList refactor

README.md, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/app/ui/image_list.py, src/nrtk_explorer/app/ui/layout.py
The start of this epic: https://github.com/Kitware/nrtk-explorer/issues/89
=> feat(transforms): add CLI arg for inference models

src/nrtk_explorer/app/images/images.py, src/nrtk_explorer/app/transforms.py, src/nrtk_explorer/library/dataset.py
Can test with
`nrtk-explorer --server --dataset uoft-cs/cifar10 beans`
Depends on:
=> Image Classification Datasets

docs/source/manual/DEVELOPMENT.rst
Fixes https://github.com/Kitware/nrtk-explorer/issues/185
=> docs: fix npm install instructions
