Kitware/nrtk-explorer

nrtk_explorer/app/core.py
nrtk_explorer/app/embeddings.py
nrtk_explorer/app/transforms.py

Refactor aesthetic of the parameters UI for the core and embedding subapp

cosmetic fixes in embeddings and core parameters UI

---

nrtk_explorer/app/embeddings.py
nrtk_explorer/app/transforms.py
nrtk_explorer/library/embeddings_extractor.py
nrtk_explorer/library/images_manager.py
tests/test_embeddings.py

In this PR I add several things:
- I extracted the bits from #41 to make sure that we work with visdrone dataset (fixed image id selection).
- I reworked how we resize images and the different type of images that we save, I change the schema of image types and sizes that we store as shown in the diagram below.
- I heavily refactored image_manager module.
- ~I added the commit from #43 to fix reactivity so we can have all the changes in one go.~
```mermaid
graph TD;
OriginalImage-->Thumbnail;
OriginalImage--->OriginalTransformation;
Thumbnail-->ImageForModel;
Thumbnail-->ThumbnailTransformation;
ThumbnailTransformation-->TransformationForModel;
```

Rework image storage scheme

---

src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/library/object_detector.py
vue-components/src/components/ImageDetection.vue

* When selecting a set of images, some of which share the same image shape, the bouding boxes could be on the wrong image.
* The horse drawn trolly thing in the sample dataset has a category ID of 0, which caused a JS error.  Not sure about root cause...

Image list fixes: Bounding boxes image missmatch, Unknown annotation category

---

.github/workflows/create_release.yaml
.github/workflows/push_to_release.yaml

We need this since sometimes such as at #65 we only wanted to backport a few fixed, however, our current prepare_to_release will bring every main commit to release anyways.

ci: create_release only in release branch

---

src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/library/nrtk_transforms.py

This is needed since pybsm requires OpenGL native libraries installed which is not the case in some of our target deployment systems
cc @jourdain

fix: gracefully disable nrtk transform if we have import error

---

src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/image_ids.py
src/nrtk_explorer/app/image_meta.py
src/nrtk_explorer/app/parameters.py
src/nrtk_explorer/app/trame_utils.py
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/app/ui/image_list.py
src/nrtk_explorer/app/ui/layout.py
src/nrtk_explorer/library/coco_utils.py
src/nrtk_explorer/library/dataset.py
src/nrtk_explorer/library/nrtk_transforms.py
src/nrtk_explorer/library/object_detector.py
src/nrtk_explorer/widgets/nrtk_explorer.py
tests/test_object_detector.py
vue-components/src/components/ImageDetection.vue
vue-components/src/types/index.ts

Ground Truth and Annotation Score tweeks

---

.github/workflows/ci.yml

We need this to make sure that we do not lose compatibility with the newer versions of our dependencies.

ci: add nightly build

---

src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/embeddings.py
src/nrtk_explorer/app/trame_utils.py
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/app/ui/__init__.py
src/nrtk_explorer/app/ui/image_list.py

Does not compute transformed images if column is hidden.

Image List visible column control

---

pyproject.toml
src/nrtk_explorer/library/nrtk_transforms.py

We are failing the mypi test due to pybsm changing from darkCurrentFromDensity to dark_current_from_density function name in the latest releases.

fix(transforms): parametrize pybsm darkCurrentFromDensity call

---

examples/conda-env-cuda.yml

Adds an example conda env file that install nrtk-explorer with cuda

conda: add conda env that includes cuda pytorch

---

pyproject.toml
src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/image_server.py
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/library/dataset.py
tests/test_dataset.py

I could not figure out how to "trick" nebari into using nrtk-explorer from pip correctly even if it works in my local machine. I went to plan B and edited the dataset module to inject a simple class that mimics kwcoco if kwcoco does not exists.

dataset: set kwcoco as optional

---

src/nrtk_explorer/app/filtering.py
src/nrtk_explorer/app/ui/image_list.py

Adds a slider to ajust image size:
Relabels ground truth annotation category filter to button from "Apply" to "Select Images."

Image size slider for image list

---

pyproject.toml

nrkt put opencv-python under an extra in 0.12.0 https://github.com/Kitware/nrtk/releases/tag/v0.12.0

fix(deps): add nrtk[headless] extra to fix runtime error

---

README.md
list.py
pyproject.toml
src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/embeddings.py
src/nrtk_explorer/app/images/images.py
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/library/dataset.py
tests/test_dataset.py

Test it out:
`nrtk-explorer --dataset cppe-5 beans rafaelpadilla/coco2017 keremberke/german-traffic-sign-detection mrtoy/mobile-ui-design keremberke/construction-safety-object-detection keremberke/table-extraction`
Use the `--download` CLI arg to cache the Hugging Face dataset localy.  Dataset streaming is the default.
`nrtk-explorer --dataset cppe-5 --download`
Adds a `dataset[vision]` dependency.
Object Detection task tagged datasets:
https://huggingface.co/datasets?task_categories=task_categories:object-detection
Does not support them all =/

Hugging Face Datasets

---

src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/embeddings.py
src/nrtk_explorer/app/filtering.py
src/nrtk_explorer/app/ui/image_list.py
vue-components/src/components/FilterOptionsWidget.vue

Now, the image list always shows the selected images.  So now all images are selected after loading dataset or clicking on blank space in embeddings plot.  Also, when the Category filter turns up no images, no images are shown in the image list.

Category filter tweeks

---

pyproject.toml
src/nrtk_explorer/library/annotations.py
src/nrtk_explorer/library/dataset.py
tests/test_dataset.py

#156 implicitly makes kwcoco a required dependency, this PR explicitly makes it a required dependency, and removes the fallback class `JsonDataset`

Make kwcoco a required dependency

---

README.md
pyproject.toml
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/library/nrtk_transforms.py
src/nrtk_explorer/library/nrtk_transforms.yaml
src/nrtk_explorer/library/yaml_transforms.py
tests/test_transforms.py

PR pins the versions of  `nrtk` and `pybsm`.  These packages often have breaking changes.  This means our testing cron job is less interesting, but keeping it still: https://github.com/Kitware/nrtk-explorer/blob/main/.github/workflows/ci.yml#L7
closes #152
After release on PiPy, update Conda feedstock: https://github.com/conda-forge/nrtk-explorer-feedstock/pull/16

Update nrtk and pybsm version

---

README.md
src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/export.py
src/nrtk_explorer/app/ui/__init__.py
src/nrtk_explorer/app/ui/collapsible_card.py
src/nrtk_explorer/app/ui/layout.py
src/nrtk_explorer/library/dataset.py
src/nrtk_explorer/widgets/nrtk_explorer.py
vue-components/src/components/ExportWidget.vue
vue-components/src/components/index.js

Add ability to export transformed dataset

---

src/nrtk_explorer/app/core.py
src/nrtk_explorer/app/embeddings.py
src/nrtk_explorer/app/images/annotations.py
src/nrtk_explorer/app/images/images.py
src/nrtk_explorer/app/transforms.py
src/nrtk_explorer/app/ui/image_list.css
src/nrtk_explorer/app/ui/image_list.py
src/nrtk_explorer/library/multiprocess_predictor.py
src/nrtk_explorer/library/object_detector.py
src/nrtk_explorer/library/predictor.py
tests/test_object_detector.py
tests/test_predictor.py

After updating the images visible in the image list, all other selected images are updated and their scores computed.
After images are scored, the table sort may have changed the images that are visible, so ImageList is asked to send visible image IDs again, which may trigger a new `_update_all_images` if the set of images in view has changed.
`transformers.pipeline` is not async, so we run that in subprocess via `multiprocess_predictor.py`

Fix sorting on scores

---

src/nrtk_explorer/app/embeddings.py

and use saved params when ploting new transformed images.
Also, cache transformed images to re-plot then when embedding params are changed.
Closes #170
Closes #171

fix(embeddings): save embeddings params on compute

---

src/nrtk_explorer/app/embeddings.py
src/nrtk_explorer/library/embeddings_extractor.py
src/nrtk_explorer/library/multiprocess_predictor.py
vue-components/src/components/ScatterPlot.vue

App should figure out batch size automatically by
catching out of memory errors.
It is easier to see image relationships in 2D plot.

embeddings: remove batch size parameter and default to 2D

---

src/nrtk_explorer/library/dataset.py

In kwcoco 0.5.4 support was added to read/write data from/to compressed zipfiles. This can greatly impact the size of the kwcoco files on disk, as there is a lot of redundant information in the json files. This is especially true when the data contains polygon segmentations. 
The way this works is by reading / writing the json file to a standard location inside the zipfile. 
Inside kwcoco reading and writing to json or zip is implicit by default, although it can be controlled. The default rule is: if it looks like a zipfile (via `zipfile.is_zipfile(path)`, which quickly checks for a magic number in the header of the file) then check if there is a single readable json file inside it, and load that instead. For writing with `CocoDataset.dump`, if `compress='auto'`, it will write to a …

feat (dataset): allow zipped kwcoco files
